# apiVersion: v1
# kind: Service
# metadata:
#   name: auth-container
#   namespace: default
# spec:
#   selector:
#     app: auth-container
#   type: NodePort
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
# FCGPTHMCSCIDRKWHTATFMFCIGHIP
