apiVersion: v1
kind: Service
metadata:
  name: auth-container
  namespace: default
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  selector:
    app: auth-container
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
