apiVersion: v1
kind: Service
metadata:
  name: frontend-container
  namespace: default
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  selector:
    app: frontend-container
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
